name: shellsnake # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: a simple game # 79 char long summary
description: |
  A simple terminal based game for Linux.

grade: stable #must be 'stable' to release into candidate/stable channels
confinement: strict  #use 'strict' once you have the right plugs and slots

parts:
  shellsnake:
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    build-packages:
      - libgtest-dev
      - libncurses5-dev
      - libx11-dev
    stage-packages:
      - libncursesw5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6

layout:
  /var/shellsnake/settings.bin:
    bind-file: $SNAP_DATA/var/lib/shellsnake/settings.bin
  /var/shellsnake/scores.bin:
    bind-file: $SNAP_DATA/var/lib/shellsnake/scores.bin
  /usr/local/share/shellsnake/logo.txt:
    bind-file: $SNAP/usr/local/share/shellsnake/logo.txt

apps:
  shellsnake:
    command: usr/local/bin/snake
    plugs:
      - x11
