name: shellsnake # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: a simple game # 79 char long summary
description: |
  A simple terminal based game for Linux.

grade: devel #must be 'stable' to release into candidate/stable channels
confinement: devmode  #use 'strict' once you have the right plugs and slots

parts:
  shellsnake:
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    build-packages:
      - libgtest-dev
      - libncurses5-dev
apps:
  shellsnake:
    command: usr/local/bin/snake

